name: Deploy Static Website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Disable host key checking and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
          cybersenda@95.216.217.3 \
          "cd /home/cybersenda/cybersenda.com/public && git pull origin master"
