name: Deploy Static Website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no cybersenda@95.216.217.3 \
          "cd /home/cybersenda/cybersenda.com/public && git pull origin master"
