name: Deploy Static Website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy via SSH
      run: |
        sshpass -p "x2V$1n@9Tx2@" ssh -o StrictHostKeyChecking=no \
        -o PreferredAuthentications=password -o PubkeyAuthentication=no \
        cybersenda@95.216.217.3 \
        "cd /home/cybersenda/cybersenda.com/public && git pull origin master"
